version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.13-alpine3.17
    volumes:
    - postgres:/data/postgres
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - '${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT}'
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    restart: always

volumes:
  postgres:
  pgadmin: